[project]
name = "testpack"
version = "0.0.1"
authors = [
  { name="Thomas Bettencourt", email="thabettencourt@gmail.com" },
]
description = "A small example package"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/pypa/testpack"
"Bug Tracker" = "https://github.com/pypa/testpack/issues"